stages: [build, deploy]

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_NOLOGO: "true"
  PUBLISH_DIR: "publish"
  SSH_HOST: "145.223.83.80"
  SSH_USER: "root"

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet restore
    - dotnet build -c Release --no-restore
    - dotnet publish -c Release --no-build -o $PUBLISH_DIR
    - ls -la $PUBLISH_DIR
  artifacts:
    expire_in: 1 hour
    paths:
      - $PUBLISH_DIR/


deploy:
  stage: deploy
  image: alpine:3.20
  dependencies: [build]
  only:
    - master
  before_script:
    - apk add --no-cache openssh-client rsync
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts
  script:
    - rsync -az --delete -e "ssh -p ${SSH_PORT:-22}" $PUBLISH_DIR/ ${SSH_USER}@${SSH_HOST}:/home/root/jobby/
    
    - ssh -p ${SSH_PORT:-22} ${SSH_USER}@${SSH_HOST} "systemctl restart jobby && systemctl status jobby --no-pager"
